windows-rdp:
  tags:
    - saas-windows-amd64
  timeout: 5h
  script:
    - Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
    - netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
    - Restart-Service -Name TermService -Force
    - $securePass = ConvertTo-SecureString "Password@123" -AsPlainText -Force
    - New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
    - Add-LocalGroupMember -Group "Administrators" -Member "RDP"
    - Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
    - Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "$env:TEMP\tailscale.msi"
    - Start-Process msiexec.exe -ArgumentList "/i", "$env:TEMP\tailscale.msi", "/quiet", "/norestart" -Wait
    - & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=tskey-auth-khcLqb6wNu11CNTRL-zwiZEn4T48bw7VTTP2778brxktfNeekUZ --hostname=gitlab-rdp
    - $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
    - Write-Host "IP=$tsIP User=RDP Pass=Password@123"
    - while ($true) { Start-Sleep -Seconds 300 }
  shell: powershell
